### ISSUE TITLE
Subnav not working

### ISSUE THREAD

**Issue by Rev8Crew** [adamnurdin01/corenav#13]
When I create 2 coreNav at one page, toggle bar button on mobile resolution not working

`$('#main_menu').coreNavigation({
            menuPosition: fixLaptop ? "right" : "center",
            container: true,
            dropdownEvent: 'hover',
        });
$('#sub_menu').coreNavigation({
            menuPosition: fixLaptop ? "right" : "center",
            container: true,
            dropdownEvent: 'hover',
        });`

**Comment by adamnurdin01** [comment]
Hi can you give yout HTML code also ?

**Comment by adamnurdin01** [comment]
Corenav not design for multiple navigation
