### ISSUE TITLE
How to close megamenu using JS click outside menu detection

### ISSUE THREAD

**Issue by clotted** [adamnurdin01/corenav#2]
Can you advise how to close megamenu using JS click outside menu detection?
(possible enhancement)

Eg. to remove the overlay. 
(this prevents mouseover detection of below elements)

Request to use JS detection of click outside the dropdown menu.
(The below JS is just example)

html:
```
    <ul class="menu">
        <li class="megamenu">
            <a href="#">Megamenu</a>
            <div id="megamenu-id" class="megamenu-content megamenu-product">
                <!-- Start Menu -->
```
Javascript:
```
<script type="text/javascript">
// Get the target
var menu = document.getElementById('megamenu-id');
// When the user clicks anywhere outside of the menu, close it
window.onclick = function(event) {
    if (event.target == menu) {
        // ## Add function here to toggle the menu 
    }
}
</script>
```

**Comment by adamnurdin01** [comment]
if you want to remove overlay detection you can just remove it by css like this
.dropdown-overlay{
    display:none !important;
}
i can't remove overlay for this feature, because it's will needed for next feature 

if you want to add any function after initial script, you can add it on "onInit" event, like this 
onInit: function(){
        window.onclick = function(event) {
        $('.core-nav .dropdown').removeClass('open');
        $('.core-nav .megamenu').removeClass('open');
        $('.dropdown-overlay').removeClass('open-dropdown');
        $('.core-nav').removeClass('open-dropdown');
        $('.core-nav').removeClass('open-responsive');      
        $('.core-responsive-slide').removeClass('open');   
    }
}

**Comment by clotted** [comment]
Thanks. Do you have an example of how this can work using "oninit" ? (I couldn't get to work)
Eg correct way to define '`var menu`', then '`if (event.target != menu)`... '
