### ISSUE TITLE
Disable Animation no effect on responsive dropdown

### ISSUE THREAD

**Issue by clotted** [adamnurdin01/corenav#3]
Using Megamenu, when in responsive mode, the setting:
'animated' has no effect. 
Tried both the following settings, but no difference.
  	 animated: false,
	 responsideSlide: false,

**How to disable slide-down of responsive menu?**
(so no animation, need to just show menu)

![2018-08-16 01_08_37](https://user-images.githubusercontent.com/32529147/44178083-f6528b00-a0f0-11e8-9422-c304e9acf14d.gif)

**Comment by adamnurdin01** [comment]
jus remove transition style on wrap menu

`@media (max-width: 992px)
.core-nav .wrap-core-nav-list {
transition: none !important;
}`
