### ISSUE TITLE
Dropdown-overlay

### ISSUE THREAD

**Issue by H-Nguyenx** [adamnurdin01/corenav#4]
Hi, I'm using corenav 1.1.3
This is my javascript
    $('nav').coreNavigation({
      menuPosition: "right", // left, right, center, bottom
      container: true, // true or false
      dropdownEvent: "hover", // Hover, Click & Accordion
      mode: "sticky",
      responsideSlide: true,
    });
When I open sidebar menu, there is a div class="dropdown-overlay open-dropdown" cover the whole document. I do not know why and purpose of this!

**Comment by adamnurdin01** [comment]
class dropdown-overlay just for overlay content, it's will detect when user click outside menu and will close dropdown-menu, mega-menu or side menu on responsive screen

i provide it for requirement next feature.

**Comment by H-Nguyenx** [comment]
I see :)
But I ran into an issue with it: 
I set my corenav mode to "sticky"; dropdownEvent to "hover". If I scroll the page down, whenever I move my mouse inside the  li.dropdown, the .dropdown-menu flash on and off continuously.
If I delete the .dropdown-overlay, it goes back to normal: just showing up, not flashing

**Comment by adamnurdin01** [comment]
Sorry i didn't find it, can you give me some image or code ?

**Comment by dschafth** [comment]
I experience similar issues. With this setting 
`            $('nav').coreNavigation({
                menuPosition: "center", // left, right, center, bottom
                mode: 'fixed',
                dropdownEvent: 'hover',
                container: true, // true or false
            });` 
the menu item for the dropdown menu works fine, but in the submenu the items are not clickable.
When dropdownEvent is changed to `hover`, the submenu flashes on and off when hovering the menu item for the dropdown menu.
Both cases work fine when .dropdown-overlay is removed.
This happens in Google Chrome. In Firefox you don't see the submenu flashing. But with console.log in  onOpenDropdown and onCloseDropdown set you see many open and close messages in the console.
