### ISSUE TITLE
dropdown is not working with bootstrap 4.1

### ISSUE THREAD

**Issue by 3h5a9** [adamnurdin01/corenav#5]
Hello
I am trying to use the nav with bootstrap 4. but the dropdown menu is not working properly with bootstrap. dropdown open in the same line.
is their any solution for that.

Thank you

**Comment by H-Nguyenx** [comment]
I think you should use one of the two: bootstrap menu or corenav, not both.

**Comment by 3h5a9** [comment]
@H-Nguyenx Thank you for your replay. I'll definitely check check.

**Comment by marcelmarty** [comment]
Change all classes from ".dropdown-menu" to ".core-nav-dropdown-menu" fixes the issue. You have to change this in CSS- and JS-files. (see my pull request)

I use corenav and this hack with bootstrap 4.3.1

**Comment by adamnurdin01** [comment]
updated in new version 1.1.5
