### ISSUE TITLE
Links on toggle button are not working

### ISSUE THREAD

**Issue by ivshin365** [adamnurdin01/corenav#6]
there is a problem in mobile size, The links in the toggle button are not clickable.

<nav hidden>
    <div class="nav-header">
        <a href="#" class="brand">
            <img src="./assets/img/brand.png" />
        </a>
        <button class="toggle-bar">
            <span class="fa fa-bars"></span>
        </button>	
    </div>								
    <ul class="menu">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Service</a></li>
        <li><a href="#">Contact Us</a></li>
    </ul>
</nav>
 
$('nav').coreNavigation({
    menuPosition: "right", // left, right, center, bottom
    container: true, // true or false
    mode: 'fixed',
    onInit: function(){
        console.log('Init coreNav');
    }
});

$(window).on('scroll', function(){
    if($(window).scrollTop() > 0){
        $('nav').addClass('scrolled');
    }else{
        $('nav').removeClass('scrolled');
    }
});
		

please help me with this issue

**Comment by adamnurdin01** [comment]
update in new version 1.1.5
